### ISSUE TITLE
Branch names prevent use with the test suite

### ISSUE THREAD

**Issue by andrewbonney** [AMWA-TV/nmos-api-security#19]
It would be useful if this repo could follow the branch naming conventions from https://github.com/amwa-tv/nmos/wiki/GitHub-Workflow, otherwise the test suite will fail to load it correctly. As I'd guess there's the potential for the two BCPs to move forward at different rates with respect to versioning, it may be that ultimately there need to be two repositories used instead.

**Comment by simonrankine** [comment]
Resolved
