### ISSUE TITLE
"version" in x-nmos-api private claim

### ISSUE THREAD

**Issue by garethsb-sony** [AMWA-TV/nmos-api-security#23]
Currently the [BCP-003-02 description of the `x-nmos-api` private claim](https://github.com/AMWA-TV/nmos-api-security/blob/v1.0-dev/best-practice-authorisation.md#x-nmos-api) has:

```json
"x-nmos-api": {
  "name": "is-04",
  "version": ["1.0","1.1","1.2"]
}
```

Would it make sense to be consistent with other NMOS specifications (e.g. [IS-04 Node /self resource](https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.2.x/examples/nodeapi-self-get-200.json) `"api"` property), like so:

```json
"x-nmos-api": {
  "name": "is-04",
  "versions": ["v1.0","v1.1","v1.2"]
}
```

**Comment by FOXNEOAdvancedTechnology** [comment]
That seems reasonable - please draft PR.
