### ISSUE TITLE
File naming 🇬🇧 🇺🇸

### ISSUE THREAD

**Issue by garethsb-sony** [AMWA-TV/nmos-api-security#25]
To finish off dd52cee0efb7147f19cc236b85325ab85c1a0a33, it might be appropriate to rename best-practice-authorisation.md to best-practice-authorization.md... or best-practice-auth.md 😉

**Comment by bgilmer77** [comment]
best-practice-auth.md?  Avoid the whole issue??

**Comment by garethsb-sony** [comment]
Yes, I did offer that suggestion, but I notice it's already [APIs/AuthorizationAPI.raml](https://github.com/AMWA-TV/nmos-api-security/blob/v1.0-dev/APIs/AuthorizationAPI.raml) and [APIs/schemas/authorization-base.json](https://github.com/AMWA-TV/nmos-api-security/blob/v1.0-dev/APIs/schemas/authorization-base.json) so having the 'z' in the doc name would be consistent with those.

¯\\_(ツ)_/¯

I would make a PR for this but it'd be nice if #22 would be merged first.

**Comment by FOXNEOAdvancedTechnology** [comment]
Without objection, group is OK with best-practice-authorization.md please make PR
