### ISSUE TITLE
BCP-003-01: TLS 1.2 required cipher suites

### ISSUE THREAD

**Issue by garethsb-sony** [AMWA-TV/nmos-api-security#27]
Should BCP-003-01 [TLS 1.2 Cipher Suites](https://github.com/AMWA-TV/nmos-api-security/blob/v1.0-dev/best-practice-secure-comms.md#tls-12-cipher-suites) be explicit about overruling [RFC 5246 Section 9. Mandatory Cipher Suites](https://tools.ietf.org/html/rfc5246#section-9)? I think it's OK, just might be worth a note.

**Comment by FOXNEOAdvancedTechnology** [comment]
Requesting Sony to draft a note and do PR

**Comment by garethsb-sony** [comment]
Covered by #38.
