### ISSUE TITLE
BCP-003-01: Name matching between DNS-SD names and cert CN/SANs

### ISSUE THREAD

**Issue by garethsb-sony** [AMWA-TV/nmos-api-security#28]
Not sure where to note this, but one thing for implementers to bear in mind is that names returned from DNS-SD seem often to have the trailing '.' that indicates an FQDN (e.g. "mocks.testsuite.nmos.tv."), whereas certs are normally issued with CN/SANs that are DNS names without the (implied...) trailing '.' (e.g. "mocks.testsuite.nmos.tv"). Name matching needs to take this into account, although RFC 2818 does not make it clear.

('transferred' from https://github.com/AMWA-TV/nmos-testing/issues/207)

**Comment by FOXNEOAdvancedTechnology** [comment]
Request Sony to draft a note and make a PR
