### ISSUE TITLE
BCP-003-002: Add option of placing Access Token in URL Params for WebSocket authenticaiton

### ISSUE THREAD

**Issue by dannymeloy** [AMWA-TV/nmos-api-security#36]
I think it would be good to allow the option of passing access-tokens in the query parameters of the URL when initiating a WebSocket connection. This is due to the limitations of the Javascript API not allowing custom HTTP headers upon instantiation. Something along the lines of:

```
The Access Token SHOULD be passed in using the HTTP Header during the initial websocket handshake. When this is not feasible, the Access Token MAY be passed in using the URL parameters.
```

This is with the provision that HTTPS / WSS is always used. The only downside to this solution is that URL strings are sometimes cached, non-encrypted, in some proxy servers. Alternatives include using a ticketing system (https://stackoverflow.com/questions/4361173/http-headers-in-websockets-client-api) however this would involve changes to the IS-04 API's which seems intrusive. Another option is for the access token to be passed in as the first message after a successful websocket connection, however this means a connection is set up implicitly before authorization has taken place.

Interesting article on Websockets and Authorizaiton;
http://lucumr.pocoo.org/2012/9/24/websockets-101/

**Comment by garethsb-sony** [comment]
I think we could refer to the section of RFC 6750 that gives the "access_token" Query URI parameter as a fall-back for clients that are unable to send an Authorization header.

https://tools.ietf.org/html/rfc6750#section-2.3.

**Comment by FOXNEOAdvancedTechnology** [comment]
Danny to write up pull request based on the above comment from Gareth and discussions at the workshop.

**Comment by NEOAdvancedTechnology** [comment]
Been resolved by PR
