### ISSUE TITLE
BCP-003-002: schemas required for Access JWT

### ISSUE THREAD

**Issue by simonlo-sony** [AMWA-TV/nmos-api-security#37]
Currently we don't have schemas associated with the access token, i.e. invalid elements could end up being used.

Followings are a number of issues found in the access token:
1. JWS is signed with RS256, not RS512. JWS MUST be signed with RSASSA-PKCS1-v1_5 using SHA-512.
2. "alg" in header shall be RS512 (details as shown in 1 above).
3. should "scope" in payload be set the same as x-nmos-api's "name".
4. should "aud" in payload  constains the fully resolved domain name of the intended recipient.
5. when Bearer token is reserved via the Password flow, will it be better to use the same scope style as the access token's scope (is-04, is-05)?

Following is an exanple which was reserved via the Authorization Code Grant flow:

HEADER:
```json
{
  "alg": "RS256", 
  "typ": "JWT"
}
```
PAYLOAD:
```json
{
  "sub": "amwa",
  "exp": 1560945966,
  "scope": null,
  "iss": "http://rd.bbc.co.uk/x-nmos/auth/v1.0/",
  "iat": 1560945906,
  "x-nmos-api": {
    "access": null,
    "name": null
  },
  "nbf": 1560945906,
  "aud": null
}
```

**Comment by garethsb-sony** [comment]
Hi Danny, I think there's still a fair bit more work in this area for the specification in terms of defining the format of the payload, or am I wrong?

**Comment by dannymeloy** [comment]
You're definitely not wrong. Sorry Gareth that appears to be because I used the word `resolve` in the description of the branch I've just merged within my Auth Server repo.. it wasn't intentional.

**Comment by garethsb-sony** [comment]
Ha, yes - slightly surprising to me that GitHub does that automatic closing of issues even across repos!!

**Comment by FOXNEOAdvancedTechnology** [comment]
Danny to revise Simon's original list of potential authorization flows based on our experience to date to come up with some schema proposals.  To be put on Basecamp, let AMWA members speak up about which ones they reject and which ones they like.

**Comment by NEOAdvancedTechnology** [comment]
Perhaps JWT schemas will be in IS-10.  Still under evaluation.

**Comment by NEOAdvancedTechnology** [comment]
See https://github.com/AMWA-TV/nmos-authorization/pull/11
