### ISSUE TITLE
BCP-003-01: Need AMWA guidance on certificate provisioning

### ISSUE THREAD

**Issue by garethsb-sony** [AMWA-TV/nmos-api-security#44]
Feedback from several vendors is that they see certificate deployment and automatic renewal before expiry as a big blocker to adoption of secure communications (HTTPS/WSS) with NMOS APIs.

Simon's [BBC Whitepaper 338](https://www.bbc.co.uk/rd/publications/whitepaper338) covers several possibilities for certificate provisioning, including SCEP with NDES, which is pragmatically covered well here: https://blogs.technet.microsoft.com/jeffbutte/2016/12/16/236/.

Offering guidance to the industry on this topic could encourage adoption of secure communications with NMOS.

**Comment by NEOAdvancedTechnology** [comment]
I notice that the white paper says "While widely used the SCEP protocol is outdated, and only capable of provision RSA certificates meaning it cannot support the latest elliptic curve algorithms. The EST algorithm may provide a good alternative, if adoption is good enough to make it widely deployable."  Also see: https://en.wikipedia.org/wiki/Enrollment_over_Secure_Transport

**Comment by andrewbonney** [comment]
I've added a few notes and links to https://github.com/AMWA-TV/nmos-api-security/blob/dannym-drafts/security-drafts/cert_deployment.md

The impression I get is certainly that of the options available, EST is the most suitable at present. If we wished to make recommendations along those lines we would need to establish some best practice, particularly around discovery and initial authentication of the EST server and client.

**Comment by NEOAdvancedTechnology** [comment]
We'll give EST a try: https://github.com/AMWA-TV/nmos-api-security/pull/47

**Comment by NEOAdvancedTechnology** [comment]
Moving forward with EST.
