### ISSUE TITLE
BCP-003-03: Documment EST TODOs

### ISSUE THREAD

**Issue by JamesGibo** [AMWA-TV/nmos-api-security#60]
Log a list of possible TODO items as an issue for prosperity as they have been removed from BCP-003-03 ready for its publication:

# TODO:

- [x] - Consider mandating that a new private key is generated for certificate renewals, for security and preventing issues with EST servers re-issuing existing certs if CSR is un-changed
- [ ] - Issues could arise when renewing certificate if the EST client is unable to replace the TLS certificate without causing system disruption - group needs to come up with recommendation on best practices for this.  Perhaps a /renew-certs endpoint for use to trigger process when it is safe to do so
- Consider using using TLS Client Certificates when using NMOS API, for use with BCP-003-02 OAuth
- Consider including unique information in the manufacturer client certificate, such as MAC address, so the EST Server can validate that the client certificate presented was for the device in question (eg. the firmware has not been loaded onto a fake device)
- Use of 802.1AR - secure device identity for a distinct PKI for client Auth
- Define the use of Root CA Key Update, for Root CA rollover/renewal
- Possible extensions to EST RFC
  - Add method to signal certificate profile, eg. TLS Client Auth or TLS Server Auth
  - Add method to signal profile for server side key generation, digital signature algorithm
  - Discovery of EST API

**Comment by JamesGibo** [comment]
https://scotthelme.co.uk/impending-doom-root-ca-expiring-legacy-clients/

**Comment by NEOAdvancedTechnology** [comment]
Group concurs with new private key generated for certificate renewals.  Create PR.

TLS Client Certificate issue needs to be tried out before being placed in a spec.

Regarding unique information in the manufacturer client certificate, MAC address might not always be appropriate.  Group needs to think about what kind of unique information to include.

Encourage participants to look at 802.1AR and consider whether it should be used in the security spec.

CA rollover issue could end up in revised BCP-003-01.

**Comment by JamesGibo** [comment]
I believe most of these issues have now been covered or replaced with issues in the certificate provisioning repository, so this issue can now be closed.

**Comment by peterbrightwell** [comment]
Closed on group call
