### ISSUE TITLE
Items for discussion

### ISSUE THREAD

**Issue by FOXNEOAdvancedTechnology** [AMWA-TV/nmos-api-security#7]
Regarding best-practice-tls-pki.md, the following items may need some discussion:

Line 226: Regarding self-signed certs, "This SHOULD NOT be used for large installations", I suspect implementers will ask "what does LARGE mean?"  It might be good to instead suggest why this is a bad or unscalable idea.

Line 259: "Servers SHALL NOT accept or respond to plain HTTP requests."  It might be good to add language to be clear we are not presenting HTTP web pages on a device (may be useful for Identification or other purposes), but the HTTP restriction is only for API implementations as per the scope of this document.

Line 270: "Servers SHALL validate all request payloads and reject those that are invalid
with HTTP response code xxx."  I would suggest "with an appropriate 4xxx Client Error code" as there are a number of ways that an request payload could be invalid.  For example 403 Forbidden, 405 Method Not Allowed, 406 Not Acceptable, perhaps even 402 Payment Required, or the generic 400 Bad Request.  I'm not even sure if we should be specifying code 405 on line 265, as it should be an obvious HTTP/REST thing to do.

Line 413: "Creators of new AMWA Interface Specifcations SHOULD ensure that the recommendations of this document are included in the Specification itself."  Do we really want Specification writers to copy/paste this document, or simply reference it in future Specifications?

-Thomas

**Comment by peterbrightwell** [comment]
Thanks Thomas, my answers as follows:

226: Agree, will reword

259: Yes, web pages are beyond the scope but I can make it clearer we're only talking about APIs here. (Though of course these days all web pages really should be served with HTTPS as well.)

270: Agreed. Also the OWASP cheat sheet provides a helpful list of relevant ones, so I'll reference that.

413: Will reword to say "...are followed..."

**Comment by peterbrightwell** [comment]
See PR #8
